package com.san.tmts.dataobjects;

import java.util.Date;

/**
 * Projectusers generated by MyEclipse Persistence Tools
 */

public class ProjectusersDO extends com.san.tmts.dataobjects.BaseDO implements
		java.io.Serializable {

	// Fields

	private ProjectusersId id;

	// Constructors

	/** default constructor */
	public ProjectusersDO() {
	}

	/** minimal constructor */
	public ProjectusersDO(ProjectusersId id) {
		this.id = id;
	}

	/** full constructor */
	public ProjectusersDO(ProjectusersId id, Date creationDate,
			Integer creationPersonId, Date lastupdateDate,
			Integer lastupdatePerdonId) {
		this.id = id;		
	}

	// Property accessors

	public ProjectusersId getId() {
		return this.id;
	}

	public void setId(ProjectusersId id) {
		this.id = id;
	}
		
}