package com.san.tmts.dataobjects;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by MyEclipse Persistence Tools
 */

public class UsersDO extends com.san.tmts.dataobjects.BaseDO  {

	// Fields

	private Integer userId;

	private String userName;

	private String password;

	private String email;

	private Set tasksesForAssignedPerson = new HashSet(0);

	private Set tasklists = new HashSet(0);

	private Set projects = new HashSet(0);

	private Set tasksesForCreationPersonId = new HashSet(0);

	// Constructors

	/** default constructor */
	public UsersDO() {
	}

	/** minimal constructor */
	public UsersDO(Integer userId, String userName, String password, String email) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.email = email;
	}

	/** full constructor */
	public UsersDO(Integer userId, String userName, String password,
			String email, Date creationDate, Integer creationPersonId,
			Date lastupdateDate, Date lastupdatePerdonId,
			Set tasksesForAssignedPerson, Set tasklists, Set projects,
			Set tasksesForCreationPersonId) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.email = email;		
		this.tasksesForAssignedPerson = tasksesForAssignedPerson;
		this.tasklists = tasklists;
		this.projects = projects;
		this.tasksesForCreationPersonId = tasksesForCreationPersonId;
	}

	// Property accessors

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getTasksesForAssignedPerson() {
		return this.tasksesForAssignedPerson;
	}

	public void setTasksesForAssignedPerson(Set tasksesForAssignedPerson) {
		this.tasksesForAssignedPerson = tasksesForAssignedPerson;
	}

	public Set getTasklists() {
		return this.tasklists;
	}

	public void setTasklists(Set tasklists) {
		this.tasklists = tasklists;
	}

	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

	public Set getTasksesForCreationPersonId() {
		return this.tasksesForCreationPersonId;
	}

	public void setTasksesForCreationPersonId(Set tasksesForCreationPersonId) {
		this.tasksesForCreationPersonId = tasksesForCreationPersonId;
	}

}