package com.san.my.dataobj;

import java.util.Date;

/**
 * TransactionDO generated by MyEclipse Persistence Tools
 */

public class TransactionDO implements java.io.Serializable {

	// Fields

	private Integer transId;

	private AccountsDO accounts;

	private SlipDO slip;

	private Date datetime;

	private Double amount;

	private String transFlow;

	private Integer transType;

	private String description;

	// Constructors

	/** default constructor */
	public TransactionDO() {
	}

	/** minimal constructor */
	public TransactionDO(Integer transId, AccountsDO accounts, Date datetime,
			Double amount, String transFlow, Integer transType) {
		this.transId = transId;
		this.accounts = accounts;
		this.datetime = datetime;
		this.amount = amount;
		this.transFlow = transFlow;
		this.transType = transType;
	}

	/** full constructor */
	public TransactionDO(Integer transId, AccountsDO accounts, SlipDO slip,
			Date datetime, Double amount, String transFlow, Integer transType,
			String description) {
		this.transId = transId;
		this.accounts = accounts;
		this.slip = slip;
		this.datetime = datetime;
		this.amount = amount;
		this.transFlow = transFlow;
		this.transType = transType;
		this.description = description;
	}

	// Property accessors

	public Integer getTransId() {
		return this.transId;
	}

	public void setTransId(Integer transId) {
		this.transId = transId;
	}

	public AccountsDO getAccounts() {
		return this.accounts;
	}

	public void setAccounts(AccountsDO accounts) {
		this.accounts = accounts;
	}

	public SlipDO getSlip() {
		return this.slip;
	}

	public void setSlip(SlipDO slip) {
		this.slip = slip;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public Double getAmount() {
		return this.amount;
	}

	public void setAmount(Double amount) {
		this.amount = amount;
	}

	public String getTransFlow() {
		return this.transFlow;
	}

	public void setTransFlow(String transFlow) {
		this.transFlow = transFlow;
	}

	public Integer getTransType() {
		return this.transType;
	}

	public void setTransType(Integer transType) {
		this.transType = transType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}