package com.san.my.dataobj;

import java.util.HashSet;
import java.util.Set;

/**
 * SeedsDO generated by MyEclipse Persistence Tools
 */

public class SeedsDO implements java.io.Serializable {

	// Fields

	private Integer seedId;

	private String name;

	private Set slips = new HashSet(0);

	// Constructors

	/** default constructor */
	public SeedsDO() {
	}

	/** minimal constructor */
	public SeedsDO(Integer seedId, String name) {
		this.seedId = seedId;
		this.name = name;
	}

	/** full constructor */
	public SeedsDO(Integer seedId, String name, Set slips) {
		this.seedId = seedId;
		this.name = name;
		this.slips = slips;
	}

	// Property accessors

	public Integer getSeedId() {
		return this.seedId;
	}

	public void setSeedId(Integer seedId) {
		this.seedId = seedId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getSlips() {
		return this.slips;
	}

	public void setSlips(Set slips) {
		this.slips = slips;
	}

}