package com.san.my.dataobj;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SlipDO generated by MyEclipse Persistence Tools
 */

public class SlipDO implements java.io.Serializable {

	// Fields

	private Integer slipId;

	private AccountsDO accounts;

	private SeedsDO seeds;

	private Date datetime;

	private String farmarName;

	private String farmarVillage;

	private Integer bags;

	private Integer looseBag;

	private Integer barthi;

	private Double rate;

	private Double qtls;

	private Double hamaliRate;

	private Double adthiRate;

	private Double ccRate;

	private String description;

	private Set transactions = new HashSet(0);

	// Constructors

	/** default constructor */
	public SlipDO() {
	}

	/** minimal constructor */
	public SlipDO(Integer slipId) {
		this.slipId = slipId;
	}

	/** full constructor */
	public SlipDO(Integer slipId, AccountsDO accounts, SeedsDO seeds, Date datetime,
			String farmarName, String farmarVillage, Integer bags,
			Integer looseBag, Integer barthi, Double rate, Double qtls,
			Double hamaliRate, Double adthiRate, Double ccRate,
			String description, Set transactions) {
		this.slipId = slipId;
		this.accounts = accounts;
		this.seeds = seeds;
		this.datetime = datetime;
		this.farmarName = farmarName;
		this.farmarVillage = farmarVillage;
		this.bags = bags;
		this.looseBag = looseBag;
		this.barthi = barthi;
		this.rate = rate;
		this.qtls = qtls;
		this.hamaliRate = hamaliRate;
		this.adthiRate = adthiRate;
		this.ccRate = ccRate;
		this.description = description;
		this.transactions = transactions;
	}

	// Property accessors

	public Integer getSlipId() {
		return this.slipId;
	}

	public void setSlipId(Integer slipId) {
		this.slipId = slipId;
	}

	public AccountsDO getAccounts() {
		return this.accounts;
	}

	public void setAccounts(AccountsDO accounts) {
		this.accounts = accounts;
	}

	public SeedsDO getSeeds() {
		return this.seeds;
	}

	public void setSeeds(SeedsDO seeds) {
		this.seeds = seeds;
	}

	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

	public String getFarmarName() {
		return this.farmarName;
	}

	public void setFarmarName(String farmarName) {
		this.farmarName = farmarName;
	}

	public String getFarmarVillage() {
		return this.farmarVillage;
	}

	public void setFarmarVillage(String farmarVillage) {
		this.farmarVillage = farmarVillage;
	}

	public Integer getBags() {
		return this.bags;
	}

	public void setBags(Integer bags) {
		this.bags = bags;
	}

	public Integer getLooseBag() {
		return this.looseBag;
	}

	public void setLooseBag(Integer looseBag) {
		this.looseBag = looseBag;
	}

	public Integer getBarthi() {
		return this.barthi;
	}

	public void setBarthi(Integer barthi) {
		this.barthi = barthi;
	}

	public Double getRate() {
		return this.rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	public Double getQtls() {
		return this.qtls;
	}

	public void setQtls(Double qtls) {
		this.qtls = qtls;
	}

	public Double getHamaliRate() {
		return this.hamaliRate;
	}

	public void setHamaliRate(Double hamaliRate) {
		this.hamaliRate = hamaliRate;
	}

	public Double getAdthiRate() {
		return this.adthiRate;
	}

	public void setAdthiRate(Double adthiRate) {
		this.adthiRate = adthiRate;
	}

	public Double getCcRate() {
		return this.ccRate;
	}

	public void setCcRate(Double ccRate) {
		this.ccRate = ccRate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Set transactions) {
		this.transactions = transactions;
	}

}